controller_list:
  - name: fake_robot_arm_controller
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
initial:  # Define initial robot poses.
  - group: robot_arm
    pose: home_position